[connection-wwan-metric]
match-device=interface-name:wwan0
# Force any connection profile spawning on wwan0 to have a low-priority metric
ipv4.route-metric=800
ipv6.route-metric=800
ipv4.never-default=false
ipv6.never-default=false
